# Generated by Django 4.2 on 2023-04-13 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Myapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='assignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=50)),
                ('Position', models.CharField(max_length=50)),
                ('Office', models.CharField(max_length=50)),
                ('Age', models.IntegerField()),
                ('Start_date', models.DateField()),
                ('Salary', models.IntegerField()),
            ],
        ),
        migrations.AlterField(
            model_name='student',
            name='phone_number',
            field=models.IntegerField(null=True),
        ),
    ]
