# Generated by Django 4.2 on 2023-04-14 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Myapp', '0002_assignment_alter_student_phone_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='newitem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Venue_Name', models.CharField(max_length=50)),
                ('Address', models.CharField(max_length=50)),
                ('Zip_PostCode', models.IntegerField()),
                ('Contact_Phone', models.IntegerField()),
                ('Web_Address', models.CharField(max_length=50)),
                ('Email_Address', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='olditem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Author', models.CharField(max_length=50)),
                ('Title', models.CharField(max_length=50)),
                ('Text', models.CharField(max_length=1000)),
                ('Created', models.DateTimeField()),
                ('Published_date', models.DateTimeField()),
            ],
        ),
    ]
